package thousandislands.model.enums;

public enum Aktion {
	HOLZ_MITNEHMEN, 
	LIANEN_MITNEHMEN,
	KRUG_FUELLEN,
	KORB_FUELLEN,
	KRUG_FORMEN,
	FEUER_MACHEN,
	KRUG_BRENNEN,
	KORB_FLECHTEN,
	PAPAYA_MITNEHMEN,
	TROTZDEM_MITNEHMEN,
	BAUM_FAELLEN,
	SEGEL_MITNEHMEN,
	FLOSS_BAUEN,
	RUINEN_DURCHSUCHEN,
	KOMPASS_MITNEHMEN, 
	WRACK_DURCHSUCHEN, 
	WERKZEUG_MITNEHMEN, 
	ABLADEN;
}
